version: '3.8'

services:
  db:
    image: postgres:15
    container_name: f1_db_dev
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - f1_network

  redis:
    image: redis:7-alpine
    container_name: f1_redis_dev
    restart: always
    ports:
      - "6379:6379"
    networks:
      - f1_network

  celery_worker:
    image: python:3.11-slim
    container_name: f1_celery_worker_dev
    restart: always
    command: ["celery", "-A", "backend", "worker", "-l", "info"]
    env_file:
      - .env.dev
    volumes:
      - ../backend:/app/backend
    working_dir: /app/backend
    depends_on:
      - db
      - redis
    networks:
      - f1_network

  celery_beat:
    image: python:3.11-slim
    container_name: f1_celery_beat_dev
    restart: always
    command: ["celery", "-A", "backend", "beat", "-l", "info"]
    env_file:
      - .env.dev
    volumes:
      - ../backend:/app/backend
    working_dir: /app/backend
    depends_on:
      - db
      - redis
    networks:
      - f1_network
    

volumes:
  postgres_dev_data:

networks:
  f1_network:
    driver: bridge