# Generated by Django 5.2.10 on 2026-02-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('round', models.IntegerField()),
                ('date', models.DateField()),
                ('has_sprint', models.BooleanField(default=False)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.circuit')),
            ],
            options={
                'verbose_name': 'Гран-при',
                'verbose_name_plural': 'Гран-при',
                'ordering': ['round'],
            },
        ),
    ]
