# Generated by Django 5.2.10 on 2026-02-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_circuit_grandprix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grandprix',
            options={'ordering': ['year', 'round'], 'verbose_name': 'Гран-при', 'verbose_name_plural': 'Гран-при'},
        ),
        migrations.AddField(
            model_name='grandprix',
            name='fp1_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='fp2_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='fp3_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='qualifying_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='race_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='sprint_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='sprint_qualifying_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='grandprix',
            index=models.Index(fields=['year', 'round'], name='core_grandp_year_1643af_idx'),
        ),
    ]
