# Generated by Django 5.2.14 on 2026-06-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('fp1', 'Practice 1'), ('fp2', 'Practice 2'), ('fp3', 'Practice 3'), ('sprint_qualifying', 'Sprint Qualifying'), ('sprint', 'Sprint'), ('qualifying', 'Qualifying'), ('race', 'Race')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grandprix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('user', 'race', 'session_type')},
            },
        ),
    ]
