# Generated by Django 5.2.14 on 2026-06-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='reminder_time',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='session_type',
            field=models.CharField(choices=[('fp1', 'FP1'), ('fp2', 'FP2'), ('fp3', 'FP3'), ('sprint_qualifying', 'Sprint Qualifying'), ('sprint', 'Sprint'), ('qualifying', 'Qualifying'), ('race', 'Race')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserSessionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('fp1', 'FP1'), ('fp2', 'FP2'), ('fp3', 'FP3'), ('sprint_qualifying', 'Sprint Qualifying'), ('sprint', 'Sprint'), ('qualifying', 'Qualifying'), ('race', 'Race')], max_length=30)),
                ('reminder_time', models.PositiveIntegerField(choices=[(120, '120 минут'), (60, '60 минут'), (30, '30 минут'), (20, '20 минут'), (15, '15 минут'), (10, '10 минут')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.user')),
            ],
            options={
                'indexes': [models.Index(fields=['session_type'], name='core_userse_session_c1fb65_idx'), models.Index(fields=['user'], name='core_userse_user_id_14710a_idx')],
                'unique_together': {('user', 'session_type', 'reminder_time')},
            },
        ),
    ]
