# Generated by Django 5.2.14 on 2026-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificationlog_reminder_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationlog',
            unique_together={('user', 'race', 'session_type', 'reminder_time')},
        ),
    ]
