# Generated by Django 5.2.14 on 2026-09-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notificationlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
